# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-bucket-160398320853"
    dynamodb_table = "test-160398320853-terraform-state-lock"
    encrypt        = true
    key            = "test/./terraform.tfstate"
    region         = "us-east-1"
  }
}
